services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=taxi_cluster
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
    volumes:
      - namenode:/hadoop/dfs/name
      - ../data/raw/2025:/data/raw

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    depends_on:
      hive-metastore-postgresql:
        condition: service_healthy
      namenode:
        condition: service_started
      datanode:
        condition: service_started
    ports:
      - "9083:9083"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9083 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop.env
    depends_on:
      hive-metastore:
        condition: service_healthy
    ports:
      - "10000:10000"
    volumes:
      - ../hive:/hive
    command: /opt/hive/bin/hiveserver2

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../jobs:/jobs
      - ../hive:/hive

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g  

volumes:
  namenode:
  datanode:
